version: '3.7'
services: 
  aeneas:
    image: iskoldt/aeneas:latest  # Use the built image
    volumes: 
      - .:/app 
    command: python3 -m aeneas.tools.execute_task test.mp3 test1.txt "task_language=eng|os_task_file_format=json|is_text_type=plain" map.json
